examen_parcial/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion_tareas/',include('gestion_tareas.urls')),
]

gestion_tareas/urls.py
from . import views
from django.urls import path

app_name = 'gestion_tareas'

urlpatterns = [
    path('',views.login,name='login'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('creacionTareas',views.creacionTareas,name='creacionTareas'),
    path('edicionTareas/<str:ind>',views.edicionTareas,name='edicionTareas'),
    path('vistaTareas/<str:ind>',views.vistaTareas,name='vistaTareas'),
    path('eliminarTarea/<str:ind>',views.eliminarTarea,name='eliminarTarea'),
    path('finalizarTarea/<str:ind>',views.finalizarTarea,name='finalizarTarea'),
]

gestion_tareas/models.py
from django.db import models
from datetime import date,datetime
# Create your models here.
class usuariosRegistrados(models.Model):
    nombre = models.CharField(max_length=128,default='')
    apellido = models.CharField(max_length=128,default='')
    password = models.CharField(max_length=128,default='')
    codigoUsuario = models.CharField(max_length=128,default='')
class tarea(models.Model):
    descripcion = models.CharField(max_length=128,default='')
    fechaCreacion = models.DateField(default=datetime.today())
    fechaEntrega = models.DateField(default=datetime.today())
    usuarioResponsable = models.CharField(max_length=128,default='')
    estadoTarea = models.CharField(max_length=128,default='PROGRESO')

gestion_tareas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from gestion_tareas.models import usuariosRegistrados,tarea
from django.urls import reverse
from dateutil.parser import parse
from datetime import date,datetime

# Create your views here.
def login (request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        passwordUsuario = request.POST.get('passwordUsuario')
        #Validacion de información
        usuario_registrado = 0
        usuarios_totales = usuariosRegistrados.objects.all()

        for estudiante in usuarios_totales:
            if estudiante.nombre == nombreUsuario and estudiante.password == passwordUsuario:
                usuario_registrado = 1
        if usuario_registrado == 1:
            return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
        else:
            return render(request, 'gestion_tareas/login.html',{
                'mensaje':'Los datos ingresados son incorrectos',
            })
        #Fin de validación

    return render(request,'gestion_tareas/login.html')

def dashboard (request):
    #Filtrando tareas por alumnos
    usuario_id = []
    usuario_activo = usuariosRegistrados.objects.filter(codigoUsuario='1')
    for usuario in usuario_activo:
        usuario_id.append(usuario)
    usuario_responsable = tarea.objects.filter(usuarioResponsable='1')
    for usuario in usuario_responsable:
        usuario_id.append(usuario)
    #Fin del filtrado

    #Calculo de dias restantes

    #Fin calculo

    return render(request,'gestion_tareas/dashboard.html',{
        'objtareas': usuario_id,
    })


def creacionTareas (request):
    if request.method == 'POST' :
        crear_fechaEntrega = request.POST.get('crear_fechaEntrega')
        crear_fechaEntrega = parse(crear_fechaEntrega)
        crear_descripcion= request.POST.get('crear_descripcion')
        crear_usuarioResponsable= request.POST.get('crear_usuarioResponsable')
        tarea(descripcion=crear_descripcion,fechaEntrega=crear_fechaEntrega,usuarioResponsable=crear_usuarioResponsable).save()
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
    return render(request,'gestion_tareas/creacionTareas.html')

def edicionTareas (request,ind):
    tarea_editar = tarea.objects.get(id=ind)
    if request.method == 'POST':
        fecha = request.POST.get('crear_fechaEntrega')
        descrip = request.POST.get('crear_descripcion')
        usuarioRespo = request.POST.get('crear_usuarioResponsable')
        tarea_editar.fechaEntrega = fecha
        tarea_editar.descripcion = descrip
        tarea_editar.usuarioResponsable = usuarioRespo
        tarea_editar.save()
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
    return render(request,'gestion_tareas/edicionTareas.html',{
        'tarea_info': tarea_editar,
    })

def vistaTareas (request,ind):
    tarea_editar = tarea.objects.get(id=ind)
    if request.method == 'POST':
        fecha = request.POST.get('crear_fechaEntrega')
        descrip = request.POST.get('crear_descripcion')
        usuarioRespo = request.POST.get('crear_usuarioResponsable')
        tarea_editar.fechaEntrega = fecha
        tarea_editar.descripcion = descrip
        tarea_editar.usuarioResponsable = usuarioRespo
        tarea_editar.save()
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
    return render(request, 'gestion_tareas/vistaTareas.html', {
        'tarea_info': tarea_editar,
    })

def eliminarTarea (request,ind):
    tarea_editar = tarea.objects.get(id=ind)
    if request.method == 'POST':
        fecha = request.POST.get('crear_fechaEntrega')
        descrip = request.POST.get('crear_descripcion')
        usuarioRespo = request.POST.get('crear_usuarioResponsable')
        tarea_editar.fechaEntrega = fecha
        tarea_editar.descripcion = descrip
        tarea_editar.usuarioResponsable = usuarioRespo
        tarea_editar.delete()
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
    return render(request, 'gestion_tareas/eliminarTarea.html', {
        'tarea_info': tarea_editar,
    })

def finalizarTarea (request,ind):
    tarea_editar = tarea.objects.get(id=ind)
    if request.method == 'POST':
        fecha = request.POST.get('crear_fechaEntrega')
        descrip = request.POST.get('crear_descripcion')
        usuarioRespo = request.POST.get('crear_usuarioResponsable')
        tarea_finalizada = 'FINALIZADO'
        tarea_editar.fechaEntrega = fecha
        tarea_editar.descripcion = descrip
        tarea_editar.usuarioResponsable = usuarioRespo
        tarea_editar.finalizarTarea = tarea_finalizada
        print(tarea_editar.finalizarTarea)
        tarea_editar.save()
        return HttpResponseRedirect(reverse('gestion_tareas:dashboard'))
    return render(request, 'gestion_tareas/finalizarTarea.html', {
        'tarea_info': tarea_editar,
    })

gestion_tareas/templates/gestion_tareas/creacionTareas.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body class="container">
        <div>
            <h3> Crear Tarea</h3>
            <form method="post" action="{% url 'gestion_tareas:creacionTareas' %}">
            {% csrf_token %}
                <div class="form-group col-md-8">
                    <label>Fecha entrega</label>
                    <input type="date" class="form-control" name="crear_fechaEntrega" value="datetime.now()">
                </div>
                <div class="row">
                    <div class="col">
                        <label>Descripcion</label>
                        <input type="text" class="form-control" name="crear_descripcion">
                    </div>
                    <div class="col">
                        <label>Usuario Responsable</label>
                        <input type="text" class="form-control" name="crear_usuarioResponsable">
                    </div>
                </div>
                <br>
                <div class="row">
                    <button type="submit" class="btn btn-success col"> Crear </button>
                    <a class="btn btn-danger col" href="{% url 'gestion_tareas:dashboard' %}">Salir</a>
                </div>
            </form>
        </div>
    </body>
</html>

gestion_tareas/templates/gestion_tareas/dashboard.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <br>
            <h3 style="text-align:center;">Tareas pendientes</h3>
            <br>
            <div class="float-end">
                <a class="btn btn-success" href="{% url 'gestion_tareas:creacionTareas' %}">Agregar Tarea</a>
            </div>
            <br>
            <br>
            <br>
            <table class="table table-info table-striped table-bordered">
                <thead>
                    <th>Descripcion</th>
                    <th>Fecha de creacion</th>
                    <th>Fecha de entrega</th>
                    <th>Usuario responsable</th>
                    <th>Estado de la tarea</th>
                    <th>Ver detalles</th>
                    <th>Editar</th>
                    <th>Eliminar</th>
                </thead>
                <tbody>
                    {% for tarea in objtareas %}
                    <tr>
                        <td>{{ tarea.descripcion }}</td>
                        <td>{{ tarea.fechaCreacion }}</td>
                        <td>{{ tarea.fechaEntrega }}</td>
                        <td>{{ tarea.usuarioResponsable }}</td>
                        <td>{{ tarea.estadoTarea }}</td>
                        <td><a class="btn btn-success" href="{% url 'gestion_tareas:vistaTareas' tarea.id %}" >D</a></td>
                        <td><a class="btn btn-info" href="{% url 'gestion_tareas:edicionTareas' tarea.id %}" >E</a></td>
                        <td>
                            <a class="btn btn-danger" href="{% url 'gestion_tareas:eliminarTarea' tarea.id %}" >X</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </body>
</html>

gestion_tareas/templates/gestion_tareas/edicionTareas.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Editar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body class="container">
        <div>
            <h3> Editar Tarea</h3>
            <form method="post" action="{% url 'gestion_tareas:edicionTareas' tarea_info.id %}">
            {% csrf_token %}
                <div class="form-group col-md-8">
                    <label>Fecha entrega</label>
                    <input type="date" class="form-control" name="crear_fechaEntrega" value="{{ tarea_info.fechaEntrega}}">
                </div>
                <div class="row">
                    <div class="col">
                        <label>Descripcion</label>
                        <input type="text" class="form-control" name="crear_descripcion" value="{{ tarea_info.descripcion}}">
                    </div>
                    <div class="col">
                        <label>Usuario Responsable</label>
                        <input type="text" class="form-control" name="crear_usuarioResponsable" value="{{tarea_info.usuarioResponsable}}">
                    </div>
                </div>
                <br>
                <div class="row">
                    <button type="submit" class="btn btn-success col"> Crear </button>
                    <a class="btn btn-danger col" href="{% url 'gestion_tareas:dashboard' %}">Salir</a>
                </div>
            </form>
        </div>
    </body>
</html>

gestion_tareas/templates/gestion_tareas/eliminarTarea.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Editar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body class="container">
        <div>
            <h3> Eliminar Tarea</h3>
            <form method="post" action="{% url 'gestion_tareas:eliminarTarea' tarea_info.id %}">
            {% csrf_token %}
                <div class="form-group col-md-8">
                    <label>Fecha entrega</label>
                    <input type="date" class="form-control" name="crear_fechaEntrega" value="{{ tarea_info.fechaEntrega|date:'Y-m-d'}}">
                </div>
                <div class="row">
                    <div class="col">
                        <label>Descripcion</label>
                        <input type="text" class="form-control" name="crear_descripcion" value="{{ tarea_info.descripcion}}">
                    </div>
                    <div class="col">
                        <label>Usuario Responsable</label>
                        <input type="text" class="form-control" name="crear_usuarioResponsable" value="{{tarea_info.usuarioResponsable}}">
                    </div>
                </div>
                <br>
                <div class="row">
                    <button onclick="alert('Se va eliminar la tarea')" type="submit" class="btn btn-success col"> Eliminar </button>
                    <a class="btn btn-danger col" href="{% url 'gestion_tareas:dashboard' %}">Salir</a>
                </div>
            </form>
        </div>
    </body>
</html>

gestion_tareas/templates/gestion_tareas/finalizarTarea.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Editar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body class="container">
        <div>
            <h3> Finalizar Tarea</h3>
            <form method="post" action="{% url 'gestion_tareas:finalizarTarea' tarea_info.id %}">
            {% csrf_token %}
                <div class="form-group col-md-8">
                    <label>Fecha entrega</label>
                    <input type="date" class="form-control" name="crear_fechaEntrega" value="{{ tarea_info.fechaEntrega|date:'Y-m-d'}}">
                </div>
                <div class="row">
                    <div class="col">
                        <label>Descripcion</label>
                        <input type="text" class="form-control" name="crear_descripcion" value="{{ tarea_info.descripcion}}">
                    </div>
                    <div class="col">
                        <label>Usuario Responsable</label>
                        <input type="text" class="form-control" name="crear_usuarioResponsable" value="{{tarea_info.usuarioResponsable}}">
                    </div>
                </div>
                <br>
                <div class="row">
                    <button type="submit" class="btn btn-success col"> Finalizar </button>
                    <a class="btn btn-danger col" href="{% url 'gestion_tareas:dashboard' %}">Salir</a>
                </div>
            </form>
        </div>
    </body>
</html>

gestion_tareas/templates/gestion_tareas/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Gestion de tareas</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body style="text-align: center;">
        <br>
        <h3 class="text-info bg-dark">Ingreso gestion de tareas</h3>
        <form method="post" action="{% url 'gestion_tareas:login' %}">
        {% csrf_token %}
            <div class="container cold-md-8">
                <div class = 'form-group'>
                    <label>Usuario</label>
                    <input class = 'form-control' type="text" name="nombreUsuario" placeholder="Ingresa tu usuario">
                </div>
                <div class = 'form-group'>
                    <label>Password</label>
                    <input class = 'form-control' type="password" name="passwordUsuario" placeholder="Ingresa tu contraseña">
                </div>
                <br>
                <div class = 'form-group'>
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                </div>
            </div>
        </form>
        <br>
        {% if mensaje %}
        <div style="text-align:center;">
            <h6>{{ mensaje }}</h6>
        </div>
        {% endif %}
    </body>
</html>

gestion_tareas/templates/gestion_tareas/vistaTareas.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Editar</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body class="container">
        <div>
            <h2 style="text-align:center;"> Vista tarea detallada</h2>
            <div class="float-end">
                <a class="btn btn-success" href="{% url 'gestion_tareas:finalizarTarea' tarea_info.id %}">Finalizado</a>
            </div>
            <br>
            <form method="post" action="{% url 'gestion_tareas:vistaTareas' tarea_info.id %}">
            {% csrf_token %}
                <table class="table table-info table-striped table-bordered">
                <thead>
                    <th>Descripcion</th>
                    <th>Fecha de creacion</th>
                    <th>Fecha de entrega</th>
                    <th>Usuario responsable</th>
                    <th>Estado de la tarea</th>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ tarea_info.descripcion }}</td>
                        <td>{{ tarea_info.fechaCreacion }}</td>
                        <td>{{ tarea_info.fechaEntrega }}</td>
                        <td>{{ tarea_info.usuarioResponsable }}</td>
                        <td>{{ tarea_info.estadoTarea }}</td>
                    </tr>
                </tbody>
            </table>
                <br>
                <div class="float-end">
                <a class="btn btn-info" href="{% url 'gestion_tareas:dashboard' %}">Atrás</a>
            </div>
            </form>
        </div>
    </body>
</html>